### ISSUE TITLE
Используй JS классы

### ISSUE THREAD

**Issue by imin314** [Azmodan95/website-toxin#15]
Сейчас js код для блоков оформлен неединообразно - где-то используешь классы, где-то функцию-конструктор, где-то просто циклом назначаешь обработчики.
Лучше везде использовать js-классы, чтобы потом уже для каждого найденного по селектору элемента создавать свой инстанс. Такой подход позволит разделить функционал по методам и сделать код более читаемым.

При этом обрати внимание, что по стандартам файл класса должен именоваться как имя экспортируемого класса. В отдельный init.js для каждого блока ты добавляешь код для поиска элементов по селектору класса и инициализации экземпляра js-класса.

**Comment by Azmodan95** [comment]
Вроде бы все исправил.
