### ISSUE TITLE
Хардкод

### ISSUE THREAD

**Issue by imin314** [Azmodan95/website-toxin#17]
Весь изменяемый текст нужно перенести в параметры миксина. Как, например, создать карточку для другого номера?
![Снимок экрана от 2020-03-27 16-19-39](https://user-images.githubusercontent.com/40715953/77741255-2d1bb180-7047-11ea-9678-87c086cf6226.png)

**Comment by Azmodan95** [comment]
Исправил, больше таких моментов не нашел.

**Comment by imin314** [comment]
В этом блоке .colors__items и .type__items нужно выводить циклом:
![Screenshot_4](https://user-images.githubusercontent.com/40715953/77813113-94357680-70d8-11ea-8bcf-00bdb91fa666.png)

Также сама страница по сути является блоком, поэтому название элементов должно начинаться с .colors-and-type. Списки с цветами и стилями заголовков надо вынести в отдельные блоки.

**Comment by Azmodan95** [comment]
Сделал.
