### ISSUE TITLE
Страница form elements

### ISSUE THREAD

**Issue by imin314** [Azmodan95/website-toxin#19]
![Screenshot_3](https://user-images.githubusercontent.com/40715953/77813730-774f7200-70dd-11ea-922b-80511a7d99ca.png)

**Comment by Azmodan95** [comment]
Исправил.

**Comment by imin314** [comment]
Стрелка куда-то уехала и нижний дропдаун всегда перекрывает верхний.
![Выделение_054](https://user-images.githubusercontent.com/40715953/79636020-01e83600-819f-11ea-9722-a4609631b5cf.png)

**Comment by Azmodan95** [comment]
Изначально исправил проблему перекрытием dropdown убрав абсолютное позиционирование. Но потом посмотрел на макет и оказалось что там все таки должно быть абсолютное позиционирование, и нечего лучше не смог придумать как поменять их местами с помощью стилей.

**Comment by imin314** [comment]
Можно было еще задать dropdown_type_facilities position: relative и z-index: 1, например.
