### ISSUE TITLE
Имена модификаторов

### ISSUE THREAD

**Issue by imin314** [Azmodan95/website-toxin#22]
В модификаторах типа отсутствует тип. Классы с префиксом js- добавляются в дополнение к обычным классам, то есть тебе надо задавать свойство объекта c модификаторами так: `dropdown-facilities js-dropdown-facilities`, но только с ключом в названии еще.
![Выделение_007](https://user-images.githubusercontent.com/40715953/78204505-e6550e00-74c3-11ea-84e9-fa013cd17ca9.png)

**Comment by imin314** [comment]
А тип модификатора не добавил.
Это почему-то самая распространенная и трудно усваиваемая ошибка.. [Почитай](https://ru.bem.info/methodology/quick-start/#%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80) еще, пожалуйста, какие 2 типа имен могут быть у модификаторов и поправь по правилам.

**Comment by Azmodan95** [comment]
Добавил, извиняюсь просто это в issues не попало.

**Comment by Azmodan95** [comment]
Я просто когда блок text-field переделывал это поправил.
![image](https://user-images.githubusercontent.com/51163508/79042612-e8287b00-7c01-11ea-9906-f85a6992771c.png)
