### ISSUE TITLE
Кавычки в свойствах объектов

### ISSUE THREAD

**Issue by imin314** [Azmodan95/website-toxin#26]
Свойства объекта нужно писать в кавычках, если оно не является валидным названием переменной в js:
![Выделение_081](https://user-images.githubusercontent.com/40715953/79042252-2c2a7880-7c20-11ea-9cc1-d7adfaeff3a2.png)

**Comment by Azmodan95** [comment]
Извиняюсь забыл поставить номер issues, из-за этого коммит в него не попал. https://github.com/Azmodan95/website-toxin/commit/813ba5e3ff6849661d9b52001abce1d7e3030518
