### ISSUE TITLE
area-label для button-like

### ISSUE THREAD

**Issue by imin314** [Azmodan95/website-toxin#35]
Сейчас такая логика, что когда пользователь еще не поставил like, скринридер прочитает "кнопка - мне не понравилось". Будто эта кнопка, чтобы поставить dislike.
Есть два способа - либо использовать атрибут area-pressed, либо переписать всю кнопку на чекбоксе (она всё-таки по семантике ближе к нему, чем к обычной кнопке).

В любом случае, заодно и поправится ошибка с тем, что параметры likeText и dislikeText указываются параллельно в pug и в js, причем в js ими никак нельзя управлять.

**Comment by Azmodan95** [comment]
Да действительно текст "Мне не понравилось" тут был лишний. С атрибутом стало намного лучше, теперь должно быть что-то вроде - кнопка "Мне понравилось" нажата или не нажата.
