### ISSUE TITLE
UI / UX

### ISSUE THREAD

**Issue by Constantine-P** [Azmodan95/website-toxin#47]
1. Добавь элементам transition
2. На мобилке раскрыть меню не получается, сразу переходит по ссылке
3. Календарь.
  3.1. Сейчас можно выбрать одну и ту же дату для прибытия и выезда. Нужно, чтобы выбрать можно было только диапазон
  3.2. Если открыть календарь и поменять разрешение (или перевернуть мобилку), календарь уезжает от инпутов
4. На 320px элементы слипаются, календарь выходит за границы экрана. Горизонтального скролла у страницы не должно быть
![image](https://user-images.githubusercontent.com/18898493/85572250-a337b080-b656-11ea-820d-45ff784f1fc3.png)

**Comment by Azmodan95** [comment]
> 1. Добавь элементам transition

Насчет этого не понятно. Зачем? В дизайне ведь он не прописан.

**Comment by Constantine-P** [comment]
Меня пугают такие резкие переходы, особенно смена фона у лэндига, включи свое чувство прекрасного )

**Comment by Azmodan95** [comment]
Сделал

**Comment by Constantine-P** [comment]
5. На странице номера картинки не ровно сейчас
![image](https://user-images.githubusercontent.com/18898493/86038727-32800200-ba63-11ea-8364-1d5c077f134b.png)

**Comment by Azmodan95** [comment]
Исправил.

**Comment by Constantine-P** [comment]
6. В хедере при клике по соглашениям открываются услуги

**Comment by Azmodan95** [comment]
Исправлено.

**Comment by Constantine-P** [comment]
3. Календарь
    3.3. Нужно, чтобы календарь закрывался при клике по кнопке применить или при клике снаружи, но не сразу после выбора даты отъезда
    3.4. Сейчас когда выбрана первая дата и курсор над ней, ячейка вся белая, сделай ей нормальные стили
7. Не плохо бы, чтобы все выпадашки закрывались при клике снаружи
8. На странице поиска номера, слайдер с фотками номера не по макету: должны появляться тени при ховере на слайдере (в макете они на первой карточке)
9. На странице поиска номера на мобилке список фильтрации нужно скрывать/показывать по аналогии с навигацией по сайту

**Comment by Azmodan95** [comment]
> 2. Не плохо бы, чтобы все выпадашки закрывались при клике снаружи

Тогда будет не соответствие макету, в макете может быть несколько их одновременно открыто.


> 4. На странице поиска номера на мобилке список фильтрации нужно скрывать/показывать по аналогии с навигацией по сайту

Задачи адаптировать сайт под мобильные устройства не было.

Все остальное исправлено.

**Comment by Constantine-P** [comment]
> Тогда будет не соответствие макету, в макете может быть несколько их одновременно открыто.

Если ты про ui kit, то это не настоящие страницы, там выпадашки раскрыты для наглядности.

> Задачи адаптировать сайт под мобильные устройства не было.
Вообще то была, иначе зачем ты скрываешь меню навигации и показываешь бургер?

**Comment by Azmodan95** [comment]
> > Тогда будет не соответствие макету, в макете может быть несколько их одновременно открыто.
> 
> Если ты про ui kit, то это не настоящие страницы, там выпадашки раскрыты для наглядности.
> 
Но задача была сверстать эти страницы, и я сделал локигу работы как на этих страницах. Какова логика работы там задумана, неизвестно.
> > Задачи адаптировать сайт под мобильные устройства не было.
>
> Вообще то была, иначе зачем ты скрываешь меню навигации и показываешь бургер?

![image](https://user-images.githubusercontent.com/51163508/86777575-ff8cce00-c061-11ea-951c-51dd14483a8b.png)
Где тут требование с мобильным видом? Скрытие меню навигации, я сделал чтобы она более менее нормально выглядела при сужении, и какая тут вообще связь?

**Comment by Constantine-P** [comment]
> Где тут требование с мобильным видом? Скрытие меню навигации, я сделал чтобы она более менее нормально выглядела при сужении, и какая тут вообще связь?

ок, убедил

**Comment by Constantine-P** [comment]
7. У нас минимальная ширина 320
![image](https://user-images.githubusercontent.com/18898493/87017652-12cea380-c1f2-11ea-9e3e-b9a931beaca2.png)

**Comment by Azmodan95** [comment]
Исправлено.
