### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Constantine-P** [Azmodan95/website-toxin#48]
1. this.handleButtonNextClick = this.handleButtonNextClick.bind(this);
    this.handleButtonPrevClick = this.handleButtonPrevClick.bind(this);
    this.handleDotClick = this.handleDotClick.bind(this);
Вместо таких штук лучше использовать какой-нибудь bind decorator или методы объявлять через свойства класса вот так:
    handleButtonPrevClick = () => { ... };

2. widthImage. По-английски корректно будет imageWidth, на крайняк widthOfImage
3. Табуляция у тебя сейчас в паг 4 пробела, в scss - 2. Лучше бы сделать везде 2
4. Все проверки содержащие более одного условия должны быть вынесены, например здесь
    if ('one' in locale && i % 10 === 1 && !(i % 100 === 11))

**Comment by Azmodan95** [comment]
Исправил.

**Comment by Constantine-P** [comment]
пункт 2 не исправил

**Comment by Azmodan95** [comment]
Исправил.
