### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by Constantine-P** [Azmodan95/website-toxin#49]
1. Это нужно автоматизировать, страниц ведь может стать и больше
    new HtmlWebpackPlugin({
      template: `${PATHS.src}/pages/index/index.pug`,
      filename: 'index.html',
      chunks: ['vendors', 'main'],
    }),
    new HtmlWebpackPlugin({
      template: `${PATHS.src}/pages/search-room/search-room.pug`,
      filename: 'search-room.html',
      chunks: ['vendors', 'main'],
    }),
    new HtmlWebpackPlugin({
      template: `${PATHS.src}/pages/room-details/room-details.pug`,
      filename: 'room-details.html',
      chunks: ['vendors', 'main'],
    }),

**Comment by Azmodan95** [comment]
Исправил.
