### ISSUE TITLE
Примеси

### ISSUE THREAD

**Issue by imin314** [Azmodan95/website-toxin#5]
Тут ты в двух случаях используешь примеси:
1) передавая значение класса через параметр миксина,
2) используя класс icon, который является другой бэм-сущностью
![Screenshot_5](https://user-images.githubusercontent.com/40715953/76760730-bec22e00-67c0-11ea-8909-39f0c181dc2a.png)

В первом случае нужно предусмотреть модификаторы в блоке advantage и передавать название модификатора в параметрах. Во втором - можно для блока icon создать миксин pug с модификаторами, а в advantage вызывать этот миксин.

Про примеси можно почитать в [стандартах](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md).

**Comment by Azmodan95** [comment]
Правильно ли я понял по первому пункту нужно сделать что-то вроде такого?
![Снимок](https://user-images.githubusercontent.com/51163508/76793134-8d079200-67d5-11ea-91d7-aeeba63ca026.PNG)
![Снимок2](https://user-images.githubusercontent.com/51163508/76792582-6432cd00-67d4-11ea-964a-ff9c023cfa7d.PNG)
Насчет второго пункта, мне не понятно как это сделать с помощью миксина. Дело в том что это стили которые нужны для правильного отображения иконки из шрифта Material Icons, эти стили добавляются везде где используются иконки из этого шрифта, и я вынес их в отдельный файл чтобы не прописывать их каждый раз. А как это все провернуть с помощью миксина?

**Comment by imin314** [comment]
По первой правке ты все правильно понял, но обрати внимание, что у тебя во всех трех случаях тэги не меняются, а отличаются только классы, которые ты навешиваешь на элемент dl.advantage__list, поэтому лучше обойтись здесь без case.

Еще я заметила, что здесь у тебя тоже блок advantage создает не один пункт, а целый список. У тебя же есть блок advantage-group, в котором ты и должен проходить циклом по массиву items и для каждого элемента массива вызывать миксин advantage. В advantage по аналогии с button нужно передавать не массив объектов, а один объект.

**Comment by imin314** [comment]
Во втором случае можно тогда поместить стили .icon в общий файл с миксинами scss и использовать [шаблонный селектор % и директиву @extend](https://sass-scss.ru/documentation/rasshirenie_css/shablonnie_selektori/).

**Comment by imin314** [comment]
По предыдущим замечаниям теперь все ок. Еще надо поправить класс.
В блоке у тебя отсутствует главный класс .advantage. Элемент .advantage__list можно сделать главным.
И .advantage__icon лучше выделить в отдельный элемент для семантики, чтобы у тебя две БЭМ сущности не висели на одном элементе.
![Screenshot_25](https://user-images.githubusercontent.com/40715953/77031504-58adf480-69d4-11ea-8bf9-7527efa9db13.png)

**Comment by Azmodan95** [comment]
Насчет вынесения иконки в отдельный элемент, но тогда весь смысл в псевдоэлементах теряется, в данном случае мы не можем вложить в список dl, не каких элементов кроме dt и dd, нам нужно будет создать обертку для этого списка и в эту обертку уже вложить элемент с иконкой и список. То же самое придется делать везде по сути где используется у меня иконка, и в итоге к примеру получится вместо такого одиночного тега `<button name="button">Текст</button>` что-то вроде такого `<div><button name="button">Текст</button><span><span></div>`. Если так более правильнее будет, я безусловно все это переделаю.

**Comment by Azmodan95** [comment]
Возможно лучше сделать иконку модификатором блока, а не его элементом?

**Comment by imin314** [comment]
Да, с модификатором действительно будет лучше. Если будут какие-то вопросы по ишьюзам, чтобы оперативнее решать, пиши в телеграм :)
