### ISSUE TITLE
Используй краткую форму записи свойств css

### ISSUE THREAD

**Issue by imin314** [Azmodan95/website-toxin#6]
Здесь, например, можно использовать свойство _font_:
![Screenshot_6](https://user-images.githubusercontent.com/40715953/76761382-ee256a80-67c1-11ea-86c1-5755e315b7e7.png)

Посмотри статью на [mdn про shorthand properties](https://developer.mozilla.org/ru/docs/Web/CSS/Shorthand_properties). Там в самом низу есть список возможных свойств.

**Comment by imin314** [comment]
Я нашла еще как минимум 5 случаев, где можно было бы использовать шорткат-свойства :) это не критичная правка, просто так css становится короче.

![Screenshot_5](https://user-images.githubusercontent.com/40715953/76826659-9f261680-684f-11ea-8ecb-27c8a451419f.png)
![Screenshot_7](https://user-images.githubusercontent.com/40715953/76826621-8c134680-684f-11ea-8645-a15d2395f4ac.png)
![Screenshot_3](https://user-images.githubusercontent.com/40715953/76826633-92092780-684f-11ea-9b79-db22d7050f0c.png)

**Comment by Azmodan95** [comment]
Вроде бы все исправил, но до конца не уверен, мог что-то упустить.

**Comment by imin314** [comment]
Я еще нашла парочку)) поиском font-size, но можешь потом по ходу поправить, если заметишь. Главное, чтобы ты знал, что есть такие свойства и умел их применять, чтобы сократить количество кода.
