### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by imin314** [Azmodan95/website-toxin#9]
Название миксина должно соответствовать названию главного класса блока.
На примере ниже для блока .bullet-list ты задаешь класс .bullet-list__items, а можно оставить просто .bullet-list.
![Screenshot_11](https://user-images.githubusercontent.com/40715953/76829977-ef54a700-6856-11ea-89bf-b6916cfa3fe0.png)

А здесь, например, блок dropdown-group, а главный класс - page__fieldset.
![Screenshot_12](https://user-images.githubusercontent.com/40715953/76830377-b537d500-6857-11ea-880d-72a5f1dd3da1.png)

**Comment by Azmodan95** [comment]
Пока что еще не все исправил.

**Comment by Azmodan95** [comment]
Вроде бы все поправил.

**Comment by imin314** [comment]
Если выражаться образно, то здесь у тебя блок вложен в элемент. Класс блока всегда должен быть первым. Ты можешь назначить <label> класс _.checkbox_, а <input> придумать главный класс _.checkbox__input_.

Ещё если input вложен в _label_, то атрибут _for_ и _id_ не нужны.
![Screenshot_26](https://user-images.githubusercontent.com/40715953/77033286-62862680-69d9-11ea-9059-d9ed7fe2dd11.png)

**Comment by imin314** [comment]
У блока не может быть свойства flex-grow, так как он не должен знать о позиционировании своего родителя. Если нужно управлять поведением блока во флекс-контейнере, то надо тоже создавать элемент-обертку.
![Выделение_038](https://user-images.githubusercontent.com/40715953/79219433-76a83100-7e7c-11ea-92c7-22e94d58b896.png)

Кстати, line-height можно задавать в кратком свойстве font через слэш после размера шрифта. Для line-height лучше использовать коэффициент, а не абсолютное значение, иначе, если изменится размер шрифта, высота строки не подстроится под него.

**Comment by imin314** [comment]
Абсолютное позиционирование тоже относится к внешнему позиционированию БЭМ-блока. Нужно вынести его в объек-обертку.
![Выделение_097](https://user-images.githubusercontent.com/40715953/80200188-782be300-864c-11ea-909b-d7a08704620b.png)

**Comment by imin314** [comment]
Страница - это тоже по сути блок. У тебя страницы начинаются с элемента:
![Выделение_113](https://user-images.githubusercontent.com/40715953/80208014-87655d80-8659-11ea-8441-bec5e03f8838.png)

**Comment by imin314** [comment]
Для всех страниц ui-kit нарушается БЭМ: блоки начинаются с элементов.
![Выделение_114](https://user-images.githubusercontent.com/40715953/80208256-06f32c80-865a-11ea-88a4-33dd9b241491.png)

Тут лучше так же, как и с pages расширять main.pug, а все содержимое обернуть в соответствующий класс, например, .cards. В нем будет .cards__logo, .cards__columns и .cards__column (сейчас у тебя класс .cards__columns называется неправильно, потому что он содержит только одну колонку).

**Comment by imin314** [comment]
> Абсолютное позиционирование тоже относится к внешнему позиционированию БЭМ-блока. Нужно вынести его в объект-обертку.
> ![Выделение_097](https://user-images.githubusercontent.com/40715953/80200188-782be300-864c-11ea-909b-d7a08704620b.png)

Здесь тоже нарушается принцип БЭМ, описанный в стандартах компании. Блок не должен менять стили другого блока:
![Выделение_121](https://user-images.githubusercontent.com/40715953/80287901-59b60c80-875e-11ea-94c8-362d4896305a.png)

**Comment by Azmodan95** [comment]
Первый коммит не к этому issues относится. Перепутал номер.
